// <auto-generated />
using LaptopShop.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaptopShop.DAL.Migrations
{
    [DbContext(typeof(LaptopShopDbContext))]
    [Migration("20260701084246_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaptopShop.DAL.Entities.Cart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Sum")
                        .HasColumnType("int");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("carts");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.CartDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CartId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("ProductId");

                    b.ToTable("cart_detail");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.Order", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ReceiverAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ReceiverName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ReceiverPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.OrderDetail", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("ProductId")
                        .HasColumnType("bigint");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("order_detail");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DetailDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Factory")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<string>("ShortDesc")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<long>("Sold")
                        .HasColumnType("bigint");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DetailDesc = "Laptop Gaming ASUS ROG cấu hình mạnh",
                            Factory = "ASUS",
                            Image = "1711078092373-asus-01.png",
                            Name = "Asus Gaming ROG",
                            Price = 20000000m,
                            Quantity = 100L,
                            ShortDesc = "Laptop Gaming ASUS ROG",
                            Sold = 10L,
                            Target = "GAMING"
                        },
                        new
                        {
                            Id = 2L,
                            DetailDesc = "Dell XPS 13 viền siêu mỏng",
                            Factory = "DELL",
                            Image = "1711078452562-dell-01.png",
                            Name = "Dell XPS 13",
                            Price = 25000000m,
                            Quantity = 50L,
                            ShortDesc = "Laptop Doanh nhân cao cấp",
                            Sold = 5L,
                            Target = "DOANH-NHAN"
                        },
                        new
                        {
                            Id = 3L,
                            DetailDesc = "Lenovo Ideapad giá rẻ",
                            Factory = "LENOVO",
                            Image = "1711079073759-lenovo-01.png",
                            Name = "Lenovo Ideapad",
                            Price = 12000000m,
                            Quantity = 200L,
                            ShortDesc = "Laptop học tập làm việc",
                            Sold = 50L,
                            Target = "SINHVIEN-VANPHONG"
                        },
                        new
                        {
                            Id = 4L,
                            DetailDesc = "Zenbook Duo tuyệt đỉnh",
                            Factory = "ASUS",
                            Image = "1711079496409-asus-02.png",
                            Name = "Asus Zenbook Duo",
                            Price = 18000000m,
                            Quantity = 30L,
                            ShortDesc = "Laptop thiết kế 2 màn hình",
                            Sold = 2L,
                            Target = "THIET-KE-DO-HOA"
                        },
                        new
                        {
                            Id = 5L,
                            DetailDesc = "Macbook Air M1 tiết kiệm pin",
                            Factory = "APPLE",
                            Image = "1711079954090-apple-01.png",
                            Name = "Macbook Air M1",
                            Price = 28000000m,
                            Quantity = 150L,
                            ShortDesc = "Macbook siêu mỏng",
                            Sold = 40L,
                            Target = "MONG-NHE"
                        },
                        new
                        {
                            Id = 6L,
                            DetailDesc = "LG Gram siêu nhẹ",
                            Factory = "LG",
                            Image = "1711080386941-lg-01.png",
                            Name = "LG Gram 14",
                            Price = 22000000m,
                            Quantity = 80L,
                            ShortDesc = "Laptop nhẹ nhất",
                            Sold = 15L,
                            Target = "MONG-NHE"
                        },
                        new
                        {
                            Id = 7L,
                            DetailDesc = "Macbook Pro hiệu năng cao",
                            Factory = "APPLE",
                            Image = "1711080787179-apple-02.png",
                            Name = "Macbook Pro M2",
                            Price = 30000000m,
                            Quantity = 60L,
                            ShortDesc = "Laptop Pro mạnh mẽ",
                            Sold = 20L,
                            Target = "DOANH-NHAN"
                        },
                        new
                        {
                            Id = 8L,
                            DetailDesc = "Acer Nitro 5 tản nhiệt mát",
                            Factory = "ACER",
                            Image = "1711080948771-acer-01.png",
                            Name = "Acer Nitro 5",
                            Price = 16000000m,
                            Quantity = 120L,
                            ShortDesc = "Laptop Gaming giá tốt",
                            Sold = 25L,
                            Target = "GAMING"
                        },
                        new
                        {
                            Id = 9L,
                            DetailDesc = "Asus Vivobook trẻ trung",
                            Factory = "ASUS",
                            Image = "1711081080930-asus-03.png",
                            Name = "Asus Vivobook",
                            Price = 14000000m,
                            Quantity = 150L,
                            ShortDesc = "Laptop mỏng đẹp",
                            Sold = 30L,
                            Target = "SINHVIEN-VANPHONG"
                        },
                        new
                        {
                            Id = 10L,
                            DetailDesc = "Dell Inspiron cho mọi nhà",
                            Factory = "DELL",
                            Image = "1711081278418-dell-02.png",
                            Name = "Dell Inspiron",
                            Price = 9000000m,
                            Quantity = 250L,
                            ShortDesc = "Laptop Dell giá rẻ",
                            Sold = 100L,
                            Target = "MONG-NHE"
                        });
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("roles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Administrator",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Normal User",
                            Name = "User"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Staff Member",
                            Name = "Staff"
                        });
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("users");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.Cart", b =>
                {
                    b.HasOne("LaptopShop.DAL.Entities.User", "User")
                        .WithOne("Cart")
                        .HasForeignKey("LaptopShop.DAL.Entities.Cart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.CartDetail", b =>
                {
                    b.HasOne("LaptopShop.DAL.Entities.Cart", "Cart")
                        .WithMany("CartDetails")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaptopShop.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cart");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.Order", b =>
                {
                    b.HasOne("LaptopShop.DAL.Entities.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.OrderDetail", b =>
                {
                    b.HasOne("LaptopShop.DAL.Entities.Order", "Order")
                        .WithMany("OrderDetails")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaptopShop.DAL.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.User", b =>
                {
                    b.HasOne("LaptopShop.DAL.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.Cart", b =>
                {
                    b.Navigation("CartDetails");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.Order", b =>
                {
                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("LaptopShop.DAL.Entities.User", b =>
                {
                    b.Navigation("Cart")
                        .IsRequired();

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
